{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "56a18726_d9f63da6",
        "filename": "tools/releasetools/ota_from_target_files.py",
        "patchSetId": 4
      },
      "lineNbr": 1410,
      "author": {
        "id": 1088085
      },
      "writtenOn": "2021-02-10T19:13:38Z",
      "side": 1,
      "message": "common.ExternalError? and you don\u0027t need the sys.exit",
      "range": {
        "startLine": 1410,
        "startChar": 12,
        "endLine": 1410,
        "endChar": 24
      },
      "revId": "408d87229fcff817319d89fb2f475d0de3a3826f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}