{
  "comments": [
    {
      "key": {
        "uuid": "0f060922_7d15b012",
        "filename": "tools/releasetools/img_from_target_files.py",
        "patchSetId": 2
      },
      "lineNbr": 100,
      "author": {
        "id": 1455782
      },
      "writtenOn": "2019-04-18T19:38:58Z",
      "side": 1,
      "message": "Without this, any future common.Cleanup() (as done in merge_target_files) will fail because input_tmp from this script will no longer exist.",
      "range": {
        "startLine": 100,
        "startChar": 0,
        "endLine": 100,
        "endChar": 47
      },
      "revId": "6abc0c5f4d11921911a27229eab325212679cf65",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5334b52f_41f84319",
        "filename": "tools/releasetools/img_from_target_files.py",
        "patchSetId": 2
      },
      "lineNbr": 100,
      "author": {
        "id": 1056365
      },
      "writtenOn": "2019-04-18T19:56:29Z",
      "side": 1,
      "message": "https://android-review.googlesource.com/c/platform/build/+/947579/2/tools/releasetools/common.py#1386 calls shutil.rmtree with ignore_errors\u003dTrue. I think it should be fine here?\n\n(It seems the shutil.rmtree at L99 should be moved to L112 under the finally there. But it\u0027s not directly related to this CL.)",
      "parentUuid": "0f060922_7d15b012",
      "range": {
        "startLine": 100,
        "startChar": 0,
        "endLine": 100,
        "endChar": 47
      },
      "revId": "6abc0c5f4d11921911a27229eab325212679cf65",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9db36e57_5c287d19",
        "filename": "tools/releasetools/img_from_target_files.py",
        "patchSetId": 2
      },
      "lineNbr": 100,
      "author": {
        "id": 1455782
      },
      "writtenOn": "2019-04-18T20:23:01Z",
      "side": 1,
      "message": "It does, but the issue is (before this added line):\n\n1. merge_target_files creates temp_dir. OPTIONS.tmpfiles now contains [temp_dir]\n\n2. img_from_target_files creates input_tmp. OPTIONS.tmpfiles now contains [temp_dir, input_tmp]\n\n3. img_from_target_files deletes input_tmp.\n\n4. merge_target_files calls common.Cleanup(), which tries to delete [temp_dir, input_tmp]. Deleting temp_dir is fine, but deleting input_tmp fails. Because input_Tmp was deleted in step 3, the \"os.path.isdir(i)\" in Cleanup() is false so it calls \"os.remove(i)\".\n\n5. os.remove(i) fails saying that there is no file or directory for input_tmp. \n\n\nAnother solution would be to change the os.remove(i) to be guarded by os.path.exists(i).",
      "parentUuid": "5334b52f_41f84319",
      "range": {
        "startLine": 100,
        "startChar": 0,
        "endLine": 100,
        "endChar": 47
      },
      "revId": "6abc0c5f4d11921911a27229eab325212679cf65",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}