{
  "comments": [
    {
      "key": {
        "uuid": "5c6a4eda_7db66f24",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 1001525
      },
      "writtenOn": "2016-03-16T19:28:07Z",
      "side": 1,
      "message": "Do we actually have code that does this?\nI remember at one point we had one line of code that did this, which I fixed and then made that warning an error.",
      "revId": "83d51c8ad1cb43cd5e0542830cf39fc9758b4480",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5c6a4eda_e002d858",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 1052399
      },
      "writtenOn": "2016-03-16T19:37:12Z",
      "side": 1,
      "message": "This warning is from clang static analyzer.\nIt\u0027s rare and I have not checked all output from all targets yet.\nI saw two at:\nexternal/sqlite/dist/sqlite3.c:72822:3: warning: Address of stack memory associated with local variable \u0027zBase\u0027 returned to caller\nexternal/sqlite/dist/sqlite3.c:108799:3: warning: Address of stack memory associated with local variable \u0027standin\u0027 returned to caller",
      "parentUuid": "5c6a4eda_7db66f24",
      "revId": "83d51c8ad1cb43cd5e0542830cf39fc9758b4480",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5c6a4eda_e075f8d3",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 1001525
      },
      "writtenOn": "2016-03-16T19:46:33Z",
      "side": 1,
      "message": "Those both seem untrue to me based on a quick look, but perhaps I\u0027m overlooking an edge case. Still, good to have those classified.",
      "parentUuid": "5c6a4eda_e002d858",
      "revId": "83d51c8ad1cb43cd5e0542830cf39fc9758b4480",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5c6a4eda_abfcc184",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 1052399
      },
      "writtenOn": "2016-03-16T21:01:17Z",
      "side": 1,
      "message": "Yes, sometime static analyzer\u0027s warning is wrong because it does not see assert or some function used by ASSERT or CHECK.",
      "parentUuid": "5c6a4eda_e075f8d3",
      "revId": "83d51c8ad1cb43cd5e0542830cf39fc9758b4480",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}