{
  "comments": [
    {
      "key": {
        "uuid": "5c6a4eda_7db66f24",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 59,
      "author": {
        "id": 1001525
      },
      "writtenOn": "2016-03-16T19:28:07Z",
      "side": 1,
      "message": "Do we actually have code that does this?\nI remember at one point we had one line of code that did this, which I fixed and then made that warning an error.",
      "revId": "83d51c8ad1cb43cd5e0542830cf39fc9758b4480",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}