{
  "comments": [
    {
      "key": {
        "uuid": "d294c103_56d750d4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1074628
      },
      "writtenOn": "2020-08-06T00:55:32Z",
      "side": 1,
      "message": "(This isn\u0027t the primary cause for the attached bug, but we believe it\u0027s likely a contributing factor for some of the cases)",
      "revId": "8fc3961f026560f537a37dd8780c83ab883b8a3c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}