{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "49b3d3c1_2ce77925",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-16T17:45:19Z",
      "side": 1,
      "message": "CheckSize should already handle the case of missing keys, is this really needed?",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e067b979_2f2bc84e",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 2052331
      },
      "writtenOn": "2023-10-19T06:21:09Z",
      "side": 1,
      "message": "Without these changes hitting below compilation Error, So need to convert a real number \n\nTraceback (most recent call last):\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/__main__.py\", line 12, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1335, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1312, in main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 596, in GenerateNonAbOtaPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 244, in WriteFullOTAPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/common.py\", line 2427, in CheckSize\nTypeError: %d format: a real number is required, not str",
      "parentUuid": "49b3d3c1_2ce77925",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bd2ed062_645a940e",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-23T18:00:30Z",
      "side": 1,
      "message": "Change \n\n```\n    limit \u003d info_dict.get(device + \"_size\")\n```\n\nto\n\n```\n    limit \u003d int(info_dict.get(device + \"_size\", 0))\n```\n\nin `CheckSize`\n\nThen you don\u0027t need to hard code partition names here",
      "parentUuid": "e067b979_2f2bc84e",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "1a2476bc_d2aa5f9f",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 2052331
      },
      "writtenOn": "2023-10-30T05:29:34Z",
      "side": 1,
      "message": "I faced below Error when I was tried int type conversation, that\u0027s why i used makeint function for those 2 partitions. \n\nTraceback (most recent call last):\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/__main__.py\", line 12, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1335, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py\", line 1312, in main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 596, in GenerateNonAbOtaPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py\", line 244, in WriteFullOTAPackage\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/ota_from_target_files/common.py\", line 2417, in CheckSize\nValueError: invalid literal for int() with base 10: \u00270x00800000",
      "parentUuid": "bd2ed062_645a940e",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ba3e43ee_ce8b0bc2",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-30T17:07:57Z",
      "side": 1,
      "message": "Use \n\n```\n    limit \u003d int(info_dict.get(device + \"_size\", 0), 0)\n```\n\nto get base auto detection",
      "parentUuid": "1a2476bc_d2aa5f9f",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "81608e13_83841a72",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 2052331
      },
      "writtenOn": "2023-10-31T06:13:43Z",
      "side": 1,
      "message": "Traceback (most recent call last):\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/__main__.py\", line 12, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/internal/stdlib/runpy.py\", line 196, in _run_module_as_main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/internal/stdlib/runpy.py\", line 86, in _run_code\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/add_img_to_target_files.py\", line 1098, in \u003cmodule\u003e\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/add_img_to_target_files.py\", line 1090, in main\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/add_img_to_target_files.py\", line 934, in AddImagesToTargetFiles\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/add_img_to_target_files.py\", line 506, in AddUserdata\n  File \"/local/mnt/workspace/LW.UM.2.1_252/out/host/linux-x86/bin/add_img_to_target_files/common.py\", line 2417, in CheckSize\nTypeError: int() can\u0027t convert non-string with explicit base\n\n\nActually int conversion needed only for these 2 partitions (vendor_boot, init_boot) ,because we are trying to add these 2 partitions inside OTA package please refer from below Gerrit line.\n\nhttps://android-review.googlesource.com/c/platform/build/+/2774647/1/tools/releasetools/non_ab_ota.py#242\n\n\nAnd Checksize is using in multiple files, Can you please reproduce from your end.\n\nThanks.",
      "parentUuid": "ba3e43ee_ce8b0bc2",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "5011ab7f_8463652e",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 1710792
      },
      "writtenOn": "2023-10-31T20:46:47Z",
      "side": 1,
      "message": "Created https://android-review.googlesource.com/c/platform/build/+/2812782",
      "parentUuid": "81608e13_83841a72",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "29158a7c_1d46e08c",
        "filename": "tools/releasetools/common.py",
        "patchSetId": 1
      },
      "lineNbr": 929,
      "author": {
        "id": 2052331
      },
      "writtenOn": "2023-11-02T05:06:29Z",
      "side": 1,
      "message": "We confirmed that With the above change compilation is successful, However i can see that we can use makeint function too.\ncan you please brief us the reason for using the above change.",
      "parentUuid": "5011ab7f_8463652e",
      "range": {
        "startLine": 928,
        "startChar": 0,
        "endLine": 929,
        "endChar": 29
      },
      "revId": "a34f23ef15c512892d12d98da9580b9f879ae70c",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}