{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f51806e0_1f38e421",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 3096390
      },
      "writtenOn": "2025-01-10T18:46:24Z",
      "side": 1,
      "message": "The Presubmit failure is expected and reveals an existing bug. The fix has been made in internal branch because the issue targets are only in internal branch.",
      "revId": "d8956e9ca29aa3e7f73c9a95907d418980d7703d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}